### ISSUE TITLE
When I try to upload srt and audio files without text, only srt is uploaded without audio. 

### ISSUE THREAD

**Issue by YrangeCat** [daxida/lingq#2]
https://github.com/daxida/lingq/blob/94a33ba323a0ac7c877db301fc71b12ed0249cbf/src/post.py#L96
When I try to upload srt and audio files without text, only the srt is uploaded without the audio.
 I will
matching_audio_filename = text_filename.replace(".txt", ".mp3")
to 
matching_audio_filename = re.sub(r"\. (txt|srt)$", ".mp3",text_filename) 
solves the problem

**Comment by daxida** [comment]
You are completely right, thank you for posting this!

I fixed it in a simpler way because I want to avoid regexes if possible, but thanks for isolating the problem too!

`matching_audio_filename = text_filename.replace(".txt", ".mp3").replace(".srt", ".mp3")`

I also added a double check to that function, much like what I already did with the pairings in `patch.py`.
